# Generated by Django 5.2.5 on 2025-08-25 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='notes',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='status',
            new_name='typem',
        ),
    ]
