# Generated by Django 5.2.5 on 2025-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgets',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='budgets',
            name='start_date',
            field=models.DateField(),
        ),
    ]
